### ISSUE TITLE
Possible contradiction regarding Exchange Online Archiving

### ISSUE THREAD

**Issue by mbender-ith** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#594] opened 2021-09-14 11:09 UTC
While https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description claims
_Microsoft 365 Business Premium includes Exchange Online Archiving subscription._
the page https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description says
Cloud-based archive and in-place hold as an add-on for the following plans [...] Microsoft 365 Business Premium

Please clarify, ideally on both pages, whether Exchange Online Archiving (or which parts of it) are already included in Microsoft 365 Business Premium.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c55dc71-81ed-864b-ac3f-63ce84688070
* Version Independent ID: 578c9a02-045e-4bf9-6384-d70560c332f0
* Content: [Exchange Online Archiving service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment] 2021-09-15 03:48
Duplicate of 595 so closing. Thanks!

**Closed by annferre** 2021-09-15 03:48 UTC
