### ISSUE TITLE
Broken link to article about message sizes

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#46] opened 2019-01-07 09:32 UTC
This link https://blogs.office.com/2015/04/15/office-365-now-supports-larger-email-messages-up-to-150-mb/ is not working any more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#message-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SKjerland** [comment] 2019-01-30 00:10
@Larryngolog - I tested the three blog post links in this article and they all correctly open the blog post. I'm going to go ahead and close this issue. Please test the link(s) again to see if the problem is resolved on your end. If you're still getting an error, please let us know. Additional details like the location of the link in the article and a description of what happens when you click it would also be very helpful. Thank you for your assistance!

**Closed by SKjerland** 2019-01-30 00:10 UTC

**Comment by CarolWangMS** [comment] 2019-04-18 08:29
I could not open the link either and I got the reason. 
The link will be redirected to local language version. You may use this link: https://www.microsoft.com/en-us/microsoft-365/blog/2015/04/15/office-365-now-supports-larger-email-messages-up-to-150-mb/

**Comment by SKjerland** [comment] 2019-04-19 00:18
@CarolWangMS - Thanks for discovering what's causing the issue. We normally use language-agnostic URLs for links so they default to the local language, but we didn't realize this causes a problem when linking to blog posts. I've fixed the issue here. The fix should be live within 24 hours.
