### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by CLBTraining** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#116] opened 2019-05-19 15:37 UTC
We use Sharepoint for a few Excel files.
I have major issues: Your point above regarding 30 meg - Is that a Sharepoint issue or Office Online issue?  When I try and upload a file larger to sharepoint I get the 30 meg error.  I understand Online cannot open such a file, but why can I not upload something bigger to my Sharepoint.  Is this a setting admin has to change?
My second question is, I want to link a cell form one Excel file to another in Documents in my Sharepoint.  All documentation says this is not possible, but in the above you say it is "External references (links)

You can refer to the contents of cells in another workbook by creating an external reference. An external reference (also called a link) is a reference to a cell or range on a worksheet in another Excel workbook, or a reference to a defined name in another workbook." Is this true and how do I do this?  We have very basic Excel files and just want to display a cell from one file in another file?  I would really appreciate your help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0d13579-5b95-82bd-4083-1919e38c034f
* Version Independent ID: 4bc5df6e-4168-3a3e-f72b-0aa327a492e8
* Content: [Excel Online](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/excel-online?fbclid=IwAR0LHkeEK9ZInPX63xR3ALCX8_Al4w6d01txUKR8_WJCISUby4lI1EPPS34#feedback)
* Content Source: [Office365-ServiceDescriptions/office-online-service-description/excel-online.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-online-service-description/excel-online.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment] 2019-06-11 23:42
@CLBTraining - Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response.

**Comment by prabita** [comment] 2019-06-11 23:42
This is a duplicate of issue 115. Closing this issue.

**Closed by prabita** 2019-06-11 23:42 UTC
