### ISSUE TITLE
Link to minutes limits is broken

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#36] opened 2018-12-07 09:44 UTC
Hello, when I click on the "For information about minute limitations in the Office 365 Domestic Calling Plan or the Office 365 International Calling Plan, click here." link I get 404 error. Where can I find information about limits for conferencing dial out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adfbc495-10f9-ae85-6486-6731d5942688
* Version Independent ID: d8d1bcec-612f-633c-e03d-e027972ed337
* Content: [Skype for Business Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/skype-for-business-online-service-description/skype-for-business-online-limits)
* Content Source: [Office365-ServiceDescriptions/skype-for-business-online-service-description/skype-for-business-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/skype-for-business-online-service-description/skype-for-business-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SKjerland** [comment] 2019-01-28 22:39
@Larryngolog - I tested the link and it correctly opens the "Country and region availability for Audio Conferencing and Calling Plans" article. I'm going to go ahead and close this issue. Please test the link again to see if the problem is resolved on your end. If you're still getting an error, please let us know. Thank you for your assistance!

**Closed by SKjerland** 2019-01-28 22:39 UTC
