### ISSUE TITLE
Office 365 Roadmap hyperlink not working

### ISSUE THREAD

**Issue by NickBazinga** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#22] opened 2018-11-14 05:36 UTC
Office 365 Roadmap hyperlink not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6177b1e-b721-39ea-25fb-0b6406cf8714
* Version Independent ID: 69864654-33a2-2669-2926-82c0433b3515
* Content: [Exchange Online Archiving Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SKjerland** [comment] 2019-01-25 21:37
@NickBazinga - I tested the link and it correctly opens the Microsoft 365 Roadmap. I'm going to go ahead and close this issue. Please test the link again to see if the problem is resolved on your end. If you're still getting an error, please let us know. Additional details like a description of what happens when you click the link would also be very helpful. Thank you for your assistance!

**Closed by SKjerland** 2019-01-25 21:37 UTC
