### ISSUE TITLE
A1 and DLP - inconsistent information

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#668] opened 2022-03-17 15:05 UTC
As per https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education
Data loss prevention (DLP) for email and files is included for A1 licenses.
![image](https://user-images.githubusercontent.com/55286035/158832304-816d7539-1abd-4489-80af-9d5ba075a246.png)

However https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-protection-data-loss-prevention-for-exchange-online-sharepoint-online-and-onedrive-for-business

States

**Which licenses provide the rights for a user to benefit from the service?**
Microsoft 365 E3/A3/Business Premium, Office 365 E3/A3, and Office 365 Data Loss Prevention and F5 Compliance and F5 Security & Compliance provide the rights for a user to benefit from Office 365 DLP for Exchange Online, SharePoint Online, and OneDrive for Business.

A1 is not mentioned.

Can this be clarified please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-protection)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment] 2022-03-24 18:41
Thank you for the feedback. I reached out to the product team and I'll keep you posted on the response. Thanks again!

**Comment by thewrabbit** [comment] 2022-05-10 09:13
Are there any updates?

**Comment by annferre** [comment] 2022-07-15 18:06
Hi there, I received a response from the product team and DLP is not available for A1. We'll be updating this page:
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education

**Comment by thewrabbit** [comment] 2022-07-19 09:22
@annferre  I don't believe they are correct - this is a significant change if they are.

See also https://m365maps.com/Microsoft%20365%20Education.pdf

DLP for email and files i.e. sharepoint/onedrive and exchange has always been available at A1 level.

**Comment by annferre** [comment] 2022-08-09 18:58
Thanks. I reached out to the product team again, and I'll let you know as soon as I get a response.

**Comment by annferre** [comment] 2022-08-19 01:48
Hi there, are you referring to 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link=blue vlink="#954F72" style='tab-interval:.5in;word-wrap:
break-word'>


<p class=MsoNormal style='background:white'><span style='font-size:12.0pt;
mso-fareast-font-family:"Times New Roman";color:black'><a id=OWAAM970076
href="mailto:v-annhem@microsoft.com"><span style='font-family:"Calibri",sans-serif;
text-decoration:none;text-underline:none'>@Ann Hemmons Ferreira (INSIGHT GLOBAL
INC)</span></a>&nbsp;perhaps customer is referring to the DLP capabilities of
O365 A1 that are documented here&nbsp;<a
href="https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice365%2Fservicedescriptions%2Foffice-365-platform-service-description%2Foffice-365-education%23microsoft-purview-compliance-portal-features&amp;data=05%7C01%7Cv-annhem%40microsoft.com%7C7f889de5733f46d6ac9a08da81844f1f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637964702549875747%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=tErLs1Fc9xdz2%2Bz1zzUePVNAGPxg6ukK1GN%2FGE%2BXYMc%3D&amp;reserved=0">Office
365 Education - Service Descriptions | Microsoft Docs</a><o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></p>



  | Office 365 Education - Service Descriptions \|   Microsoft Docs   Microsoft Office 365   is available in a variety of plans to best meet the needs of your   organization. If you're looking for the differences between the Office 365   education plans, this article will show you which features are included in   each of them. Office 365 combines the familiar Microsoft Office desktop suite   with cloud-based versions of Microsoft's next-generation communications and   ...   docs.microsoft.com
-- | --





</body>

</html>

**Comment by annferre** [comment] 2022-08-19 01:53
Are you referring to the DLP capabilities of O365 A1 that are documented here Office 365 Education - Service Descriptions | Microsoft Docs
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link=blue vlink="#954F72" style='tab-interval:.5in;word-wrap:
break-word'>


<p class=MsoNormal style='background:white'><span style='font-size:12.0pt;
mso-fareast-font-family:"Times New Roman";color:black'><a
href="https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice365%2Fservicedescriptions%2Foffice-365-platform-service-description%2Foffice-365-education%23microsoft-purview-compliance-portal-features&amp;data=05%7C01%7Cv-annhem%40microsoft.com%7C7f889de5733f46d6ac9a08da81844f1f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637964702549875747%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=tErLs1Fc9xdz2%2Bz1zzUePVNAGPxg6ukK1GN%2FGE%2BXYMc%3D&amp;reserved=0">Office
365 Education - Service Descriptions | Microsoft Docs</a><o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></p>



  | Office 365 Education -   Service Descriptions \| Microsoft Docs   Microsoft Office 365   is available in a variety of plans to best meet the needs of your   organization. If you're looking for the differences between the Office 365   education plans, this article will show you which features are included in   each of them. Office 365 combines the familiar Microsoft Office desktop suite   with cloud-based versions of Microsoft's next-generation communications and   ...   docs.microsoft.com
-- | --





</body>

</html>
[Office 365 Education - Service Descriptions | Microsoft Docs](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice365%2Fservicedescriptions%2Foffice-365-platform-service-description%2Foffice-365-education%23microsoft-purview-compliance-portal-features&data=05%7C01%7Cv-annhem%40microsoft.com%7C7f889de5733f46d6ac9a08da81844f1f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637964702549875747%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tErLs1Fc9xdz2%2Bz1zzUePVNAGPxg6ukK1GN%2FGE%2BXYMc%3D&reserved=0)

 
[Office 365 Education - Service Descriptions | Microsoft Docs](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice365%2Fservicedescriptions%2Foffice-365-platform-service-description%2Foffice-365-education%23microsoft-purview-compliance-portal-features&data=05%7C01%7Cv-annhem%40microsoft.com%7C7f889de5733f46d6ac9a08da81844f1f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637964702549875747%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tErLs1Fc9xdz2%2Bz1zzUePVNAGPxg6ukK1GN%2FGE%2BXYMc%3D&reserved=0)
Microsoft Office 365 is available in a variety of plans to best meet the needs of your organization. If you're looking for the differences between the Office 365 education plans, this article will show you which features are included in each of them. Office 365 combines the familiar Microsoft Office desktop suite with cloud-based versions of Microsoft's next-generation communications and ...
docs.microsoft.com

**Comment by thewrabbit** [comment] 2022-08-19 07:13
@annferre  - yes as per the screenshot and the link in the original post.  The service description https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education#microsoft-purview-compliance-portal-features
![image](https://user-images.githubusercontent.com/55286035/185563258-897f490c-1057-48a9-be48-9bedc1def844.png)

It's also listed at https://m365maps.com/Microsoft%20365%20Education.htm

**Comment by annferre** [comment] 2022-08-31 19:09
Hi there, we did get confirmation that DLP is not available for A1. The map owner is researching to see where the change was made. I'll keep you posted on results. Thanks again for your comment.

**Comment by thewrabbit** [comment] 2022-09-01 07:56
Thanks @annferre This is a significant change which doesn't appear to have been communicated so it would be good to get clarity - especially given the conflicting public facing information.  Organisations could have been relying on this and are unaware they're no longer compliant.

**Comment by annferre** [comment] 2022-09-12 17:37
Hi there, I received an update from the product team: we were able to get assistance with the prior Edu Biz Planner who confirmed that DLP, Litigation hold, and eDiscovery search + export were included in A1 due to Google compete (which I assume is enabled via SPO P1 EDU). There is no record or recollection in Biz Planning of that having changed, so it was likely a mistake in assuming the P1 EDU is at parity with commercial and we're revising the plan comparisons.

**Comment by thewrabbit** [comment] 2022-09-13 07:47
@annferre thanks very much for following up on this and clarifying.  Much appreciated.

**Comment by annferre** [comment] 2022-10-07 00:03
Updates are live so Closing.

**Closed by annferre** 2022-10-07 00:03 UTC

**Comment by thewrabbit** [comment] 2023-01-12 12:46
Hi @annferre 

Sorry to re-comment on this but I'm not sure what updates have been made as 

https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-15

Still doesn't include A1.
