### ISSUE TITLE
5 GB Office 365 Enterprise F1

### ISSUE THREAD

**Issue by V-ferest** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#236] opened 2019-11-25 10:36 UTC
The Storage value for Office 365 Enterprise F1 is incorrect. 
The value should be 2GB, instead of 5GB.
Customer open service request , in order to check if they should have available the 5GB

**Comment by SharS** [comment] 2019-11-25 15:40
@V-ferest Is this a duplicate of issue #235, or are you referring to a different service description article?

**Comment by V-ferest** [comment] 2019-11-25 15:41
Sorry. It's an duplicate

**Comment by SharS** [comment] 2019-11-26 00:02
@v-ferest This has been fixed. You should see the updated service description online soon.

**Closed by SharS** 2019-11-26 00:02 UTC
Labels: Microsoft submitter
