### ISSUE TITLE
Status of Services Link

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#25] opened 2018-11-19 18:02 UTC
The link does not work
https://go.microsoft.com/fwlink/p/?LinkID=270178

Located in this section: https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/service-health-and-continuity#view-status-of-services

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76358610-0b3b-49d9-6e6a-0b334b19d795
* Version Independent ID: 66466964-caa5-cded-20a6-627495521904
* Content: [Service Health and Continuity](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/service-health-and-continuity#view-status-of-services)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/service-health-and-continuity.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/service-health-and-continuity.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SKjerland** [comment] 2019-01-28 19:17
@danmyhre - I tested the link and it correctly opens the "How to check Office 365 service health" article. I'm going to go ahead and close this issue. Please test the link again to see if the problem is resolved on your end. If you're still getting an error, please let us know. Additional details like a description of what happens when you click the link would also be very helpful. Thank you for your assistance!

**Closed by SKjerland** 2019-01-28 19:17 UTC
Labels: bug

**Comment by danmyhre** [comment] 2019-01-29 01:15
Yes, it looks like "https://go.microsoft.com/fwlink/p/?LinkID=270178" was replaced with "https://docs.microsoft.com/office365/enterprise/view-service-health", which is working
